const $=s=>document.querySelector(s);
const places={
 kindergarten:{title:'Kindergarten — 5 ára',color:'#f77be2',text:'Hér er 5 ára hópurinn. Kl. 14:00 leika börnin inni á meðan eldri börnin eru í útivist. Kl. 14:45 fer Kindergarten út á meðan eldri börnin velja sér stöðvar inni.',tip:'Bleiku punktarnir á kortinu sýna 5 ára börnin.'},
 reception:{title:'Hæ, ég er hér!',color:'#68bce9',text:'Þegar þú kemur í frístund læturðu starfsfólk í skráningu vita. Þannig er hægt að hafa yfirsýn yfir hver er mættur og hjálpa öllum að finna sinn stað.',tip:'Áður en þú ferð heim læturðu líka vita.'},
 groups:{title:'Music and science',color:'#70c83e',text:'Við könnum hljóð, tónlist og vísindi. Hvað gerist ef við prófum eitthvað nýtt? Starfsfólkið hjálpar okkur að spyrja spurninga, gera tilraunir og uppgötva saman.',tip:'Þú mátt alltaf biðja um hjálp við að komast inn í leik.'},
 outside:{title:'Út í ævintýrið',color:'#b6947d',text:'Úti er pláss fyrir hreyfingu, leik og ferskt loft. Það má róla, finna upp leik eða skoða umhverfið með öðrum. Starfsfólkið úti hjálpar okkur að leika saman.',tip:'Láttu starfsfólk vita þegar þú skiptir um svæði.'},
 food:{title:'Matsalur — samkomusalurinn okkar',color:'#ffce30',text:'Matsalurinn er samkomusalur fyrir afslöppun og ærslagang. Hér getum við slakað á, spjallað, hlegið og leikið saman. Starfsfólkið hjálpar okkur að finna jafnvægi milli fjörs og rólegra stunda.',tip:'Það má vera fjör — og það má líka þurfa ró.'},
 studio:{title:'Föndur og fjör',color:'#327b37',text:'Perlur, litir, föndur, prjón og kubbar. Hugmyndir mega vera ólíkar og það þarf ekki allt að verða eins. Við prófum okkur áfram og hjálpumst að við að ganga frá.',tip:'Hér er pláss fyrir þína hugmynd.'},
 play:{title:'Leikum saman',color:'#ff783d',text:'Stundum langar okkur að spila, dansa, byggja eða bara slaka á. Við æfum okkur að hlusta, skiptast á og bjóða öðrum með. Stuðningur er til staðar þegar hans er þörf.',tip:'„Viltu vera með?“ getur verið byrjunin á góðum degi.'}
};
const titles=['Allt byrjar á halló','Ég er mætt!','Finndu þinn stað','Fólkið okkar','Við hjálpumst að','Sjáumst aftur'];
let prior;try{prior=JSON.parse(localStorage.getItem('fristund-ferd')||'null')}catch{}
const chapterFromURL=()=>{const m=location.hash.match(/^#kafli=(\d)$/);return m&&Number(m[1])<6?Number(m[1]):null};
let chapter=chapterFromURL()??(Number.isInteger(prior?.chapter)&&prior.chapter<6&&prior.chapter>=0?prior.chapter:0);const solved=new Set((prior?.solved||[]).filter(n=>Number.isInteger(n)&&n>=0&&n<6));const visited=new Set((prior?.visited||[]).filter(k=>Object.hasOwn(places,k)));
function openDetail(html){$('#detail-content').innerHTML=html;$('#detail').showModal()}
function place(key){const p=places[key];visited.add(key);openDetail(`<div class="eyebrow"><i style="--c:${p.color}"></i> KÍKTU INN</div><h2>${p.title}</h2><p>${p.text}</p><p><strong>${p.tip}</strong></p>`);if(chapter===2)render(false)}
document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>place(b.dataset.place));
$('.close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};
$('#help').onclick=()=>openDetail('<div class="eyebrow">UM LEIKINN</div><h2>Einn dagur í frístund</h2><p>Farðu í gegnum sex stutta kafla og prófaðu litlu verkefnin. Ferðin tekur um 5 mínútur, en þú ræður hraðanum.</p><p>Þú getur alltaf kíkt á kortið eða hoppað á milli kafla með strikunum neðst á síðunni. Það er í lagi að prófa aftur.</p><img src="assets/map.png" alt="Handteiknuð fyrirmynd af svæði frístundar í Landakoti">');
$('#sound').onclick=()=>{const off=document.body.classList.toggle('no-motion');$('#sound').setAttribute('aria-pressed',off);$('#sound').innerHTML=`Hreyfing: ${off?'slökkt':'kveikt'} <span>〰</span>`};
const roles=[['#f77be2','Kindergarten — 5 ára','5 ára börnin eru inni kl. 14:00 og fara í útivist kl. 14:45. Starfsfólkið fylgir hópnum í leik inni og úti.'],['#68bce9','Skráning','Öll börn eru skráð inn.'],['#327b37','Föndur og fjör','Þar sem dansinn dunar og myndirnar klippast og límast.'],['#70c83e','Music and science','Settar eru upp stöðvar og ýmist fara börnin af stað í sérverkefni eða útivist.'],['#ff783d','Stuð','Í gegnum allt starfið er starfsfólk að veita stuðning með ýmsum hætti.'],['#b6947d','Úti','Öll fara í útivist og því er mikilvægt að vera með öll viðeigandi föt fyrir það.'],['#ffce30','Matsalur','Hressing og leikur í opnu stóru rými. Hér er oft mikið um að vera.']];
function buttons(next='Áfram'){return `<button class="primary" id="next">${next} <span>→</span></button>${chapter?'<button class="back" id="back">← Til baka</button>':''}`}
function quiz(question,answers,correct,explanation){return `<p class="intro">${question}</p><div class="choices">${answers.map((a,i)=>`<button class="choice" data-answer="${i}" data-correct="${correct}">${a}</button>`).join('')}</div><div class="feedback" role="status" data-explanation="${explanation}">${solved.has(chapter)?explanation:''}</div>`}
function render(focus=true){
try{localStorage.setItem('fristund-ferd',JSON.stringify({chapter,solved:[...solved],visited:[...visited]}));}catch{}
if(window.Lif?.connected)history.replaceState(null,'','#kafli='+chapter);
window.Lif?.update({title:'Frístund',label:`${chapter+1}/6 · ${titles[chapter]}`});
let html='';
if(chapter===0)html=`<h1>Hér er pláss<br>fyrir <em>þig.</em></h1><p class="intro">Velkomin í litríka heiminn okkar.<br>Hér leikum við, prófum nýja hluti og lærum að vera saman.</p><div class="tiny-note"><span>◷</span> Um 5 mínútur · 6 litlir kaflar · Þinn hraði</div>${buttons('Förum í frístund')}<div class="welcome-bottom"><img class="rings" src="assets/rings.png" alt="Handmálaðir hringir í regnbogalitunum"><div class="handnote">Fyrir litla og stóra.<br>Og alla þar á milli.</div></div>`;
if(chapter===1)html=`<h1 class="small">Dagurinn byrjar<br>á <em>halló!</em></h1>${quiz('Þú ert komin í frístund og heyrir vini þína leika. Hvað gerirðu fyrst?',['Læt starfsfólk í skráningu vita að ég sé mætt.','Fer beint að leika án þess að láta vita.'],0,'Já! Skráning hjálpar starfsfólkinu að vita hver er á staðnum. Nú getur leikurinn hafist.')}${buttons()}`;
if(chapter===2)html=`<h1 class="small">Einn staður.<br><em>Margt að gera.</em></h1><p class="intro">Kl. 14:00 eru allir úti. Kl. 14:45 hafa börnin valið sér stöðvar. Prófaðu tímana á kortinu og kíktu inn á að minnsta kosti þrjá staði.</p><div class="choices">${Object.entries(places).map(([k,p])=>`<button class="choice" data-visit="${k}">${visited.has(k)?'✓':'↗'} ${p.title}</button>`).join('')}</div><div class="feedback" role="status">${visited.size} af ${Object.keys(places).length} stöðum skoðaðir${visited.size>=3?' — flott könnunarferð!':''}</div>${buttons()}`;
if(chapter===3)html=`<h1 class="small">Ólík hlutverk.<br><em>Eitt lið.</em></h1><p class="intro">Hér starfar fjöldi manns. Við kynnum nokkur lykilhlutverk sem vinna saman að gæðafrístund við hæfi barnanna.</p><div class="staff" aria-hidden="true">${Array.from({length:roles.length},(_,i)=>`<span class="person" style="--c:${roles[i][0]}"></span>`).join('')}</div><p class="tiny-note">Kíktu á litina og kynntu þér hlutverkin.</p><div class="role-list">${roles.map(([c,n],i)=>`<button data-role="${i}"><i style="--c:${c}"></i> ${n}</button>`).join('')}</div><p class="intro" style="font-size:14px">Starfsfólki er dreift um svæðin. Saman sköpum við örvandi og ögrandi umhverfi sem reynir á, hvetur áfram og gefur öllum tækifæri til að vaxa.</p>${buttons()}`;
if(chapter===4)html=`<h1 class="small">Getur þú<br><em>hjálpað mér?</em></h1>${quiz('Barn stendur eitt við leikinn og veit ekki hvernig það getur verið með. Hvað gætirðu gert?',['Haldið áfram án þess að segja neitt.','Boðið barninu með og beðið starfsfólk um hjálp ef þarf.'],1,'Einmitt. Við getum boðið öðrum með. Starfsfólkið hjálpar okkur ef leikurinn er erfiður eða okkur líður illa.')}${buttons()}`;
if(chapter===5)html=`<h1 class="small">Góður dagur.<br><em>Sjáumst aftur!</em></h1>${quiz('Nú er komið að því að fara heim. Hvað má ekki gleymast?',['Að ganga frá og láta starfsfólk vita að ég sé að fara.','Að fara út án þess að kveðja.'],0,'Rétt! Við göngum frá og látum vita af brottförinni. Takk fyrir daginn!')}<div id="finish">${buttons('Ljúka ferðinni')}</div>`;
$('#scene').innerHTML=`<div class="scene">${html}</div>`;$('#page-number').textContent=`0${chapter+1} / 06`;$('#chapter-label').textContent=titles[chapter];$('#chapters').innerHTML=titles.map((t,i)=>`<button class="${i===chapter?'active':solved.has(i)?'done':''}" data-chapter="${i}" aria-label="${i+1}. ${t}" ${i===chapter?'aria-current="step"':''}></button>`).join('');
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{chapter=+b.dataset.chapter;render()});
document.querySelectorAll('[data-visit]').forEach(b=>b.onclick=()=>place(b.dataset.visit));
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{const [c,n,t]=roles[+b.dataset.role];openDetail(`<div class="eyebrow"><i style="--c:${c}"></i> FÓLKIÐ OKKAR</div><h2>${n}</h2><p>${t}</p>`)});
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const good=b.dataset.answer===b.dataset.correct;$('.feedback').textContent=good?$('.feedback').dataset.explanation:'Prófum aftur. Hvað hjálpar öllum að líða vel og vita hvert af öðru?';if(good){solved.add(chapter);document.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}});
$('#next').onclick=()=>{if([1,4,5].includes(chapter)&&!solved.has(chapter)){$('.feedback').textContent='Veldu svar hér að ofan áður en þú heldur áfram.';return}if(chapter===2&&visited.size<3){$('.feedback').textContent='Kíktu inn á þrjá staði til að kynnast frístundinni.';return}solved.add(chapter);if(chapter<5){chapter++;render()}else{$('#finish').innerHTML='<h2>Þú þekkir heiminn okkar! ✳</h2><p class="intro">Láta vita. Prófa eitthvað nýtt. Bjóða með. Biðja um hjálp. Það er frístund.</p><button class="primary" id="restart">Förum aftur ↻</button>';$('#restart').onclick=()=>{chapter=0;solved.clear();visited.clear();render()}}};if($('#back'))$('#back').onclick=()=>{chapter--;render()};if(focus){$('#story').focus({preventScroll:true});if(window.innerWidth<801)$('#story').scrollIntoView({behavior:'auto'})}}
render(false);

addEventListener('hashchange',()=>{const n=chapterFromURL();if(n!==null&&n!==chapter){chapter=n;render(false)}});
addEventListener('lif:connected',()=>render(false));
