import * as THREE from './vendor/three.module.min.js';
import {buildWorld} from './world.js';
import {schoolOutline,rooms,checkpoints,church,modular,bounds,zoneAt,smallGarden} from './layout.js';
import {move,canStand} from './physics.js';
const $=s=>document.querySelector(s),canvas=$('#view');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(error){$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent='Þrívíddin þarf vafra með WebGL 2. Prófaðu nýlegan Chrome, Safari eða Firefox með vélbúnaðarhröðun.';throw error}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#dfe8de');
const scene=new THREE.Scene();scene.fog=new THREE.Fog('#dfe8de',110,210);
scene.add(new THREE.HemisphereLight('#f5f8ee','#b6bc98',2.3));
const sun=new THREE.DirectionalLight('#fff2ce',2.7);sun.position.set(20,65,-20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-70,right:70,top:80,bottom:-65,near:1,far:160});sun.shadow.bias=-.0007;scene.add(sun);
const world=buildWorld(scene,{includeUpperFloor:true}),camera=new THREE.PerspectiveCamera(55,1,.08,250);camera.rotation.order='YXZ';
let upperOn=true;
let mode='overview',roofOn=false,yaw=Math.PI/2,pitch=0,player={x:30,z:-1.5},orbit={angle:.85,elevation:.77,distance:116},lastTime=0,nearestDoor=null,currentZone='',activeCheckpoint='entrance';
const eyeHeight=1.55,keys=new Set(),stick={x:0,y:0};let drag=null,paused=false;
const events=new EventTarget();
function emit(name,detail){events.dispatchEvent(new CustomEvent(name,{detail}));window.dispatchEvent(new CustomEvent('thrividdarkort:'+name,{detail}))}
// Stable interface for the later daily simulation: it never depends on visual mesh names.
window.thrividdarkort={events,getState:()=>({mode,position:{...player},zone:zoneAt(player.x,player.z),doors:world.doors.map(d=>({id:d.id,open:d.open}))}),goTo:id=>goTo(id)};
function clearInput(){keys.clear();stick.x=stick.y=0;$('#joystick span').style.transform='';drag=null}
function setMode(next){mode=next;world.upperFloor.group.visible=mode==='overview'&&upperOn;world.upperFloor.stairs.visible=mode==='overview'&&upperOn;$('#upper-floor').disabled=mode==='walk';document.body.classList.toggle('walking',mode==='walk');$('#overview').setAttribute('aria-pressed',mode==='overview');$('#walk').setAttribute('aria-pressed',mode==='walk');$('.walk-controls').hidden=mode!=='walk';$('#mouse').hidden=mode!=='walk';$('#roof').disabled=mode==='walk';$('#roof').textContent=mode==='walk'?'Þök í göngusýn':roofOn?'Fela þök':'Sýna þök';world.roofs.visible=mode==='walk'||roofOn;$('#zoom-controls').hidden=mode!=='overview';$('#mode-label').textContent=mode==='walk'?'Í AUGNHÆÐ · 1,55 M':'YFIRLIT';$('#controls-hint').textContent=mode==='walk'?(matchMedia('(pointer:coarse)').matches?'VINSTRI · GANGA / DRAGA Á KORTI · HORFA':'W A S D · GANGA / DRAGA · HORFA / E · HURÐ / ESC · SLEPPA MÚS'):'DRAGA · SNÚA / SKRUNA · AÐDRÁTTUR';clearInput();if(mode==='overview'){document.exitPointerLock?.();$('#place-title').textContent='Skóli, kirkja og garður';$('#place-description').textContent='Dragðu til að snúa kortinu. Skrunaðu til að færa þig nær.'}else{const cp=checkpoints.find(c=>c.id===activeCheckpoint);$('#place-title').textContent=cp.name;$('#place-description').textContent=cp.description}emit('modechange',{mode})}
function goTo(id){const cp=checkpoints.find(c=>c.id===id);if(!cp)return;let [x,z]=cp.position;
 // Find a nearby clear spot if a future furniture change overlaps a checkpoint.
 if(!canStand(x,z,world.colliders,bounds)){let found=false;for(let r=.4;r<3&&!found;r+=.4)for(let a=0;a<Math.PI*2;a+=Math.PI/8)if(canStand(x+Math.cos(a)*r,z+Math.sin(a)*r,world.colliders,bounds)){x+=Math.cos(a)*r;z+=Math.sin(a)*r;found=true;break}if(!found)return}
 player={x,z};yaw=cp.yaw;pitch=0;activeCheckpoint=id;currentZone='';setMode('walk');if(innerWidth<650)$('.viewport').scrollIntoView({block:'start',behavior:'auto'});document.querySelectorAll('[data-destination]').forEach(b=>b.classList.toggle('active',b.dataset.destination===id));canvas.focus({preventScroll:true});emit('relocate',{checkpoint:id,position:{...player}})}
$('#destinations').innerHTML=checkpoints.map((c,i)=>`<button data-destination="${c.id}"><span>0${i+1}</span>${c.name}<span>↗</span></button>`).join('');document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>goTo(b.dataset.destination));
$('#zoom-in').onclick=()=>{orbit.distance=Math.max(25,orbit.distance-12)};$('#zoom-out').onclick=()=>{orbit.distance=Math.min(200,orbit.distance+12)};
$('#overview').onclick=()=>setMode('overview');$('#walk').onclick=()=>{setMode('walk');canvas.focus({preventScroll:true})};$('#reset').onclick=()=>goTo('entrance');
$('#upper-floor').onclick=()=>{upperOn=!upperOn;world.upperFloor.group.visible=upperOn;world.upperFloor.stairs.visible=upperOn;$('#upper-floor').setAttribute('aria-pressed',upperOn);$('#upper-floor').textContent=upperOn?'Fela 2. hæð':'Sýna 2. hæð'};
$('#roof').onclick=()=>{roofOn=!roofOn;world.roofs.visible=roofOn;$('#roof').setAttribute('aria-pressed',roofOn);$('#roof').textContent=roofOn?'Fela þök':'Sýna þök'};
$('#sources').onclick=()=>{document.exitPointerLock?.();paused=true;clearInput();$('#source-dialog').showModal()};$('#close-sources').onclick=()=>$('#source-dialog').close();$('#source-dialog').addEventListener('close',()=>{paused=false;clearInput()});$('#source-dialog').onclick=e=>{if(e.target===$('#source-dialog'))$('#source-dialog').close()};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.viewport').requestFullscreen()}catch{$('#controls-hint').textContent='Þessi vafri styður ekki allan skjá. Snúðu símanum fyrir breiðari sýn.'}};
$('#mouse').onclick=async()=>{try{await canvas.requestPointerLock()}catch{$('#controls-hint').textContent='Dragðu á kortinu til að horfa í kringum þig.'}};
function toggleDoor(){if(!nearestDoor)return;const d=nearestDoor;if(d.open&&Math.hypot(player.x-d.point[0],player.z-d.point[1])<.75){$('#controls-hint').textContent='Stígðu aðeins frá dyrunum áður en þú lokar þeim.';return}d.open=!d.open;d.collider.enabled=!d.open;emit('doorchange',{id:d.id,open:d.open})}
$('#door-action').onclick=()=>{toggleDoor();canvas.focus({preventScroll:true})};
window.addEventListener('keydown',e=>{if(paused||e.target.closest('button,a,dialog,input,select'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE'].includes(e.code)){e.preventDefault();keys.add(e.code)}if(e.code==='KeyE'&&!e.repeat)toggleDoor()});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();lastTime=0});document.addEventListener('pointerlockchange',()=>{clearInput();$('#mouse').textContent=document.pointerLockElement?'ESC · sleppa mús':'Músarsýn'});
canvas.addEventListener('pointerdown',e=>{if(paused)return;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY}});
canvas.addEventListener('pointermove',e=>{let dx=0,dy=0;if(document.pointerLockElement===canvas){dx=e.movementX;dy=e.movementY}else if(drag&&drag.id===e.pointerId){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY}else return;if(mode==='walk'){yaw-=dx*.004;pitch=Math.max(-1.2,Math.min(1.2,pitch-dy*.004))}else{orbit.angle-=dx*.006;orbit.elevation=Math.max(.25,Math.min(1.45,orbit.elevation+dy*.004))}});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{drag=null});
canvas.addEventListener('wheel',e=>{if(mode==='overview'){e.preventDefault();orbit.distance=Math.max(25,Math.min(165,orbit.distance+e.deltaY*.065))}},{passive:false});
const joy=$('#joystick');let joyId=null;
function updateStick(e){const r=joy.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/32,dy=(e.clientY-r.top-r.height/2)/32,n=Math.max(1,Math.hypot(dx,dy));stick.x=dx/n;stick.y=dy/n;$('#joystick span').style.transform=`translate(${stick.x*25}px,${stick.y*25}px)`}
joy.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;joy.setPointerCapture(e.pointerId);updateStick(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)updateStick(e)});for(const type of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(type,()=>{joyId=null;stick.x=stick.y=0;$('#joystick span').style.transform='' });
const svgNS='http://www.w3.org/2000/svg',mapGeometry=$('#map-geometry');function mapPolygon(points,fill){const el=document.createElementNS(svgNS,'polygon');el.setAttribute('points',points.map(p=>p.join(',')).join(' '));el.setAttribute('fill',fill);el.setAttribute('stroke','#5e7468');el.setAttribute('stroke-width','.25');mapGeometry.append(el)}
mapPolygon([[-45,-47],[45,-47],[45,95],[-45,95]],'#dce6d1');mapPolygon(schoolOutline,'#eee5ca');rooms.forEach(r=>mapPolygon(r.polygon,r.color));mapPolygon(smallGarden.polygon,'#929995');mapPolygon(smallGarden.tree.polygon,'#a9b68c');const c=church;mapPolygon([[c.x-c.width/2,c.z-c.depth/2],[c.x+c.width/2,c.z-c.depth/2],[c.x+c.width/2,c.z+c.depth/2],[c.x-c.width/2,c.z+c.depth/2]],'#b8c4c4');const m=modular;mapPolygon([[m.x,m.z],[m.x+m.width,m.z],[m.x+m.width,m.z+m.depth],[m.x,m.z+m.depth]],'#ddc49b');
const upperLabels=world.upperFloor.rooms.map(r=>({text:r.name+' · 2. hæð',upper:true,point:[r.polygon.reduce((s,p)=>s+p[0]/4,0),r.height+1.7,r.polygon.reduce((s,p)=>s+p[1]/4,0)]}));
const labelElements=[...world.labels,...upperLabels].map(l=>{const el=document.createElement('span');el.className='world-label';el.textContent=l.text;$('#world-labels').append(el);return {...l,el}});
function resize(){const r=$('.viewport').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.fov=r.width<650?72:55;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('.viewport'));resize();setMode('overview');$('#loading').hidden=true;
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#error').hidden=false;$('#error').textContent='Þrívíddartengingin rofnaði. Endurhladdu síðunni til að halda áfram.'});
function frame(time){requestAnimationFrame(frame);if(document.hidden)return;const dt=lastTime?Math.min((time-lastTime)/1000,.1):0;lastTime=time;
 if(mode==='walk'){
  if(!paused){let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-stick.y;let side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+stick.x;const norm=Math.max(1,Math.hypot(forward,side));forward/=norm;side/=norm;if(keys.has('ArrowLeft'))yaw+=dt*1.5;if(keys.has('ArrowRight'))yaw-=dt*1.5;const speed=dt*2.5;player=move(player,(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed,(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed,world.colliders,bounds)}
  camera.position.set(player.x,eyeHeight,player.z);camera.rotation.set(pitch,yaw,0,'YXZ');
  const zone=zoneAt(player.x,player.z);if(zone!==currentZone){currentZone=zone;const room=rooms.find(r=>r.id===zone);$('#place-title').textContent=room?.name||({'small-garden':'Litli garður',church:'Landakotskirkja',modular:'Lítið gámahús',park:'Landakotstún',garden:'Skólagarður','school-corridor':'Gangur · Landakotsskóli'}[zone]);emit('zoneenter',{zone,position:{...player}})}
  nearestDoor=world.doors.reduce((best,d)=>{const dist=Math.hypot(player.x-d.point[0],player.z-d.point[1]);return dist<2&&(!best||dist<Math.hypot(player.x-best.point[0],player.z-best.point[1]))?d:best},null);
 }else{camera.position.set(Math.sin(orbit.angle)*Math.cos(orbit.elevation)*orbit.distance,Math.sin(orbit.elevation)*orbit.distance,20+Math.cos(orbit.angle)*Math.cos(orbit.elevation)*orbit.distance);camera.lookAt(0,0,20);nearestDoor=null}
 $('#door-action').hidden=!nearestDoor||paused;if(nearestDoor)$('#door-action').textContent=(nearestDoor.open?'Loka':'Opna')+' · '+nearestDoor.name+' · E';
 for(const d of world.doors){const target=d.open?Math.PI/2:0;d.leaf.rotation.y=matchMedia('(prefers-reduced-motion:reduce)').matches?target:THREE.MathUtils.damp(d.leaf.rotation.y,target,10,dt)}
 $('#map-player').setAttribute('transform',`translate(${player.x} ${player.z}) rotate(${-yaw*180/Math.PI})`);
 const r=canvas.getBoundingClientRect();for(const l of labelElements){const pos=new THREE.Vector3(...l.point).project(camera);l.el.hidden=mode!=='overview'||(l.upper&&!upperOn)||pos.z>1||Math.abs(pos.x)>1||Math.abs(pos.y)>1;l.el.style.left=(pos.x+1)*r.width/2+'px';l.el.style.top=(1-pos.y)*r.height/2+'px'}
 renderer.render(scene,camera);
}
requestAnimationFrame(frame);
